import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header/Header";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Track Selector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-secondary p-3">
        <Header />
        <motion.div
          initial="hidden"
          animate="visible"
          variants={{
            hidden: {
              scale: 0.8,
              opacity: 0,
            },
            visible: {
              scale: 1,
              opacity: 1,
              transition: {
                delay: 0.4,
                duration: 3,
              },
            },
          }}
        >
          <h1 className="text-center mt-10 text-6xl">Find some great music!</h1>
        </motion.div>
      </div>
    </div>
  );
};

export default Home;
